### ISSUE TITLE
组件国际化开发建议

### ISSUE THREAD

**Issue by eJayYoung** [MST-EUI/EUI-developing-guideline#1]
- 所有组件的国际化字段统一为`locale`
- 国际化字段统一（待讨论）
 - 是统一使用`zh-cn`还是`zh_CN`

参考:
-  [ant-design 国际化组件](https://github.com/ant-design/ant-design/tree/master/components/locale-provider)
- [element-ui](https://github.com/ElemeFE/element/tree/cdee16edd4abc2a72d678b52f81e7f83d3b73296/src/locale/lang)
- [zent 国际化](https://github.com/youzan/zent/tree/66520e57b15c095601121f0c0d6d80a5839b513e/packages/zent/src/i18n)

**Comment by yukap6** [comment]
👍，已解决。国际化统一字段为 `locale`，可选值 [`zh-cn`, `en`]，默认值 `zh-cn`。
